// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Warewolf.Tools.Specs.Toolbox.Recordset.Count
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Count")]
    [NUnit.Framework.CategoryAttribute("Recordset")]
    public partial class CountFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Count.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Count", "\tIn order to count records\r\n\tAs a Warewolf user\r\n\tI want a tool that takes a reco" +
                    "rd set counts it", ProgrammingLanguage.CSharp, new string[] {
                        "Recordset"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Count a number of records in a recordset with 3 rows")]
        public virtual void CountANumberOfRecordsInARecordsetWith3Rows()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Count a number of records in a recordset with 3 rows", ((string[])(null)));
#line 8
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1753 = new TechTalk.SpecFlow.Table(new string[] {
                        "[[rs]]",
                        ""});
            table1753.AddRow(new string[] {
                        "rs().row",
                        "1"});
            table1753.AddRow(new string[] {
                        "rs().row",
                        "2"});
            table1753.AddRow(new string[] {
                        "rs().row",
                        "3"});
#line 9
 testRunner.Given("I have a recordset with this shape", ((string)(null)), table1753, "Given ");
#line 14
 testRunner.And("count on record \"[[rs()]]\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
 testRunner.When("the count tool is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 16
 testRunner.Then("the result count should be 3", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 17
 testRunner.And("the execution has \"NO\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1754 = new TechTalk.SpecFlow.Table(new string[] {
                        "Recordset"});
            table1754.AddRow(new string[] {
                        "[[rs(1).row]] = 1"});
            table1754.AddRow(new string[] {
                        "[[rs(2).row]] = 2"});
            table1754.AddRow(new string[] {
                        "[[rs(3).row]] = 3"});
#line 18
 testRunner.And("the debug inputs as", ((string)(null)), table1754, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1755 = new TechTalk.SpecFlow.Table(new string[] {
                        ""});
            table1755.AddRow(new string[] {
                        "[[result]] = 3"});
#line 23
 testRunner.And("the debug output as", ((string)(null)), table1755, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Count a number of records in a recordset with 8 rows")]
        public virtual void CountANumberOfRecordsInARecordsetWith8Rows()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Count a number of records in a recordset with 8 rows", ((string[])(null)));
#line 27
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1756 = new TechTalk.SpecFlow.Table(new string[] {
                        "rs",
                        ""});
            table1756.AddRow(new string[] {
                        "rs().row",
                        "1"});
            table1756.AddRow(new string[] {
                        "rs().row",
                        "2"});
            table1756.AddRow(new string[] {
                        "rs().row",
                        "3"});
            table1756.AddRow(new string[] {
                        "rs().row",
                        "4"});
            table1756.AddRow(new string[] {
                        "rs().row",
                        "5"});
            table1756.AddRow(new string[] {
                        "rs().row",
                        "6"});
            table1756.AddRow(new string[] {
                        "rs().row",
                        "7"});
            table1756.AddRow(new string[] {
                        "rs().row",
                        "8"});
#line 28
 testRunner.Given("I have a recordset with this shape", ((string)(null)), table1756, "Given ");
#line 38
 testRunner.And("count on record \"[[rs()]]\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 39
 testRunner.When("the count tool is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 40
 testRunner.Then("the result count should be 8", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 41
 testRunner.And("the execution has \"NO\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1757 = new TechTalk.SpecFlow.Table(new string[] {
                        "Recordset"});
            table1757.AddRow(new string[] {
                        "[[rs(1).row]] =  1"});
            table1757.AddRow(new string[] {
                        "[[rs(2).row]] =  2"});
            table1757.AddRow(new string[] {
                        "[[rs(3).row]] =  3"});
            table1757.AddRow(new string[] {
                        "[[rs(4).row]] =  4"});
            table1757.AddRow(new string[] {
                        "[[rs(5).row]] =  5"});
            table1757.AddRow(new string[] {
                        "[[rs(6).row]] =  6"});
            table1757.AddRow(new string[] {
                        "[[rs(7).row]] =  7"});
            table1757.AddRow(new string[] {
                        "[[rs(8).row]] =  8"});
#line 42
 testRunner.And("the debug inputs as", ((string)(null)), table1757, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1758 = new TechTalk.SpecFlow.Table(new string[] {
                        ""});
            table1758.AddRow(new string[] {
                        "[[result]] = 8"});
#line 52
 testRunner.And("the debug output as", ((string)(null)), table1758, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Count a number of records in a empty recordset")]
        public virtual void CountANumberOfRecordsInAEmptyRecordset()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Count a number of records in a empty recordset", ((string[])(null)));
#line 58
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1759 = new TechTalk.SpecFlow.Table(new string[] {
                        "rs",
                        ""});
            table1759.AddRow(new string[] {
                        "[[rs().row]]",
                        "NULL"});
#line 59
 testRunner.Given("I have a recordset with this shape", ((string)(null)), table1759, "Given ");
#line 62
 testRunner.And("count on record \"[[rs()]]\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 63
 testRunner.When("the count tool is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 64
 testRunner.Then("the result count should be 0", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 65
 testRunner.And("the execution has \"No\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Count a number of records in a unassigned recordset")]
        public virtual void CountANumberOfRecordsInAUnassignedRecordset()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Count a number of records in a unassigned recordset", ((string[])(null)));
#line 67
this.ScenarioSetup(scenarioInfo);
#line 68
 testRunner.Given("count on record \"[[rs()]]\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 69
 testRunner.When("the count tool is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 70
 testRunner.Then("the execution has \"An\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Count record with invalid variables")]
        public virtual void CountRecordWithInvalidVariables()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Count record with invalid variables", ((string[])(null)));
#line 73
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1760 = new TechTalk.SpecFlow.Table(new string[] {
                        "rs",
                        ""});
            table1760.AddRow(new string[] {
                        "rs().row",
                        "1"});
            table1760.AddRow(new string[] {
                        "rs().row",
                        "2"});
            table1760.AddRow(new string[] {
                        "rs().row",
                        "3"});
            table1760.AddRow(new string[] {
                        "rs().row",
                        "4"});
            table1760.AddRow(new string[] {
                        "rs().row",
                        "5"});
            table1760.AddRow(new string[] {
                        "rs().row",
                        "6"});
            table1760.AddRow(new string[] {
                        "rs().row",
                        "7"});
            table1760.AddRow(new string[] {
                        "rs().row",
                        "8"});
#line 74
 testRunner.Given("I have a recordset with this shape", ((string)(null)), table1760, "Given ");
#line 84
 testRunner.And("count on record \"[[rs().#$]]\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 85
 testRunner.When("the count tool is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 86
 testRunner.Then("the result count should be 0", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 87
 testRunner.And("the execution has \"AN\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1761 = new TechTalk.SpecFlow.Table(new string[] {
                        "Recordset"});
#line 88
 testRunner.And("the debug inputs as", ((string)(null)), table1761, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1762 = new TechTalk.SpecFlow.Table(new string[] {
                        ""});
#line 90
 testRunner.And("the debug output as", ((string)(null)), table1762, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Count only one column record")]
        public virtual void CountOnlyOneColumnRecord()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Count only one column record", ((string[])(null)));
#line 93
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1763 = new TechTalk.SpecFlow.Table(new string[] {
                        "rs",
                        ""});
            table1763.AddRow(new string[] {
                        "rs().row",
                        "1"});
            table1763.AddRow(new string[] {
                        "rs().row",
                        "2"});
            table1763.AddRow(new string[] {
                        "rs().row",
                        "3"});
            table1763.AddRow(new string[] {
                        "rs().row",
                        "4"});
            table1763.AddRow(new string[] {
                        "rs().row",
                        "5"});
            table1763.AddRow(new string[] {
                        "rs().row",
                        "6"});
            table1763.AddRow(new string[] {
                        "rs().row",
                        "7"});
            table1763.AddRow(new string[] {
                        "rs().row",
                        "8"});
#line 94
 testRunner.Given("I have a recordset with this shape", ((string)(null)), table1763, "Given ");
#line 104
 testRunner.And("count on record \"[[rs(*).row]]\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 105
 testRunner.When("the count tool is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 106
 testRunner.Then("the result count should be 0", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 107
 testRunner.And("the execution has \"AN\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1764 = new TechTalk.SpecFlow.Table(new string[] {
                        "Recordset"});
#line 108
 testRunner.And("the debug inputs as", ((string)(null)), table1764, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1765 = new TechTalk.SpecFlow.Table(new string[] {
                        ""});
#line 110
 testRunner.And("the debug output as", ((string)(null)), table1765, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Count only one coloumn record")]
        public virtual void CountOnlyOneColoumnRecord()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Count only one coloumn record", ((string[])(null)));
#line 113
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1766 = new TechTalk.SpecFlow.Table(new string[] {
                        "rs",
                        ""});
            table1766.AddRow(new string[] {
                        "rs().row",
                        "1"});
            table1766.AddRow(new string[] {
                        "rs().row",
                        "2"});
            table1766.AddRow(new string[] {
                        "rs().row",
                        "3"});
            table1766.AddRow(new string[] {
                        "rs().row",
                        "4"});
            table1766.AddRow(new string[] {
                        "fs().row",
                        "5"});
            table1766.AddRow(new string[] {
                        "fs().row",
                        "6"});
            table1766.AddRow(new string[] {
                        "fs().row",
                        "7"});
            table1766.AddRow(new string[] {
                        "fs().row",
                        "8"});
#line 114
 testRunner.Given("I have a recordset with this shape", ((string)(null)), table1766, "Given ");
#line 124
 testRunner.And("count on record \"[[rs().row]],[[fs().row]]\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 125
 testRunner.When("the count tool is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 126
 testRunner.Then("the result count should be 0", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 127
 testRunner.And("the execution has \"AN\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1767 = new TechTalk.SpecFlow.Table(new string[] {
                        "Recordset"});
#line 128
 testRunner.And("the debug inputs as", ((string)(null)), table1767, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1768 = new TechTalk.SpecFlow.Table(new string[] {
                        ""});
#line 130
 testRunner.And("the debug output as", ((string)(null)), table1768, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Count a number of records when two recordsets are defined.")]
        public virtual void CountANumberOfRecordsWhenTwoRecordsetsAreDefined_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Count a number of records when two recordsets are defined.", ((string[])(null)));
#line 133
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1769 = new TechTalk.SpecFlow.Table(new string[] {
                        "rs",
                        ""});
            table1769.AddRow(new string[] {
                        "rs().row",
                        "a"});
            table1769.AddRow(new string[] {
                        "fs().row",
                        "a"});
            table1769.AddRow(new string[] {
                        "rs().row",
                        "b"});
            table1769.AddRow(new string[] {
                        "rs().row",
                        "c"});
            table1769.AddRow(new string[] {
                        "fs().row",
                        "b"});
            table1769.AddRow(new string[] {
                        "rs().row",
                        "d"});
            table1769.AddRow(new string[] {
                        "fs().row",
                        "c"});
            table1769.AddRow(new string[] {
                        "rs().row",
                        "e"});
#line 134
 testRunner.Given("I have a recordset with this shape", ((string)(null)), table1769, "Given ");
#line 144
 testRunner.And("count on record \"[[rs()]]\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 145
 testRunner.When("the count tool is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 146
 testRunner.Then("the result count should be 5", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 147
 testRunner.And("the execution has \"NO\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1770 = new TechTalk.SpecFlow.Table(new string[] {
                        "Recordset"});
            table1770.AddRow(new string[] {
                        "[[rs(1).row]] = a"});
            table1770.AddRow(new string[] {
                        "[[rs(2).row]] = b"});
            table1770.AddRow(new string[] {
                        "[[rs(3).row]] = c"});
            table1770.AddRow(new string[] {
                        "[[rs(4).row]] =  d"});
            table1770.AddRow(new string[] {
                        "[[rs(5).row]] =  e"});
#line 148
 testRunner.And("the debug inputs as", ((string)(null)), table1770, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1771 = new TechTalk.SpecFlow.Table(new string[] {
                        ""});
            table1771.AddRow(new string[] {
                        "[[result]] = 5"});
#line 155
 testRunner.And("the debug output as", ((string)(null)), table1771, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Executing Count with two variables in result field")]
        public virtual void ExecutingCountWithTwoVariablesInResultField()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Executing Count with two variables in result field", ((string[])(null)));
#line 159
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1772 = new TechTalk.SpecFlow.Table(new string[] {
                        "rs",
                        ""});
            table1772.AddRow(new string[] {
                        "rs(1).row",
                        "1"});
            table1772.AddRow(new string[] {
                        "rs(2).row",
                        "2"});
            table1772.AddRow(new string[] {
                        "rs(3).row",
                        "3"});
            table1772.AddRow(new string[] {
                        "rs(4).row",
                        "4"});
#line 160
 testRunner.Given("I have a recordset with this shape", ((string)(null)), table1772, "Given ");
#line 166
 testRunner.And("count on record \"[[rs()]]\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 167
    testRunner.And("result variable as \"[[b]][[a]]\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 168
 testRunner.When("the count tool is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 169
 testRunner.Then("the result count should be 0", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 170
 testRunner.And("the execution has \"AN\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1773 = new TechTalk.SpecFlow.Table(new string[] {
                        "Recordset"});
            table1773.AddRow(new string[] {
                        "[[rs(1).row]] = 1"});
            table1773.AddRow(new string[] {
                        "[[rs(2).row]] = 2"});
            table1773.AddRow(new string[] {
                        "[[rs(3).row]] = 3"});
            table1773.AddRow(new string[] {
                        "[[rs(4).row]] = 4"});
#line 171
 testRunner.And("the debug inputs as", ((string)(null)), table1773, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1774 = new TechTalk.SpecFlow.Table(new string[] {
                        ""});
#line 177
 testRunner.And("the debug output as", ((string)(null)), table1774, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Ensure variables of different types produce desired results")]
        [NUnit.Framework.TestCaseAttribute("", "0", "AN", "Recordset not given", null)]
        [NUnit.Framework.TestCaseAttribute("[[var]]", "0", "AN", "Scalar not allowed", null)]
        [NUnit.Framework.TestCaseAttribute("[[q]]", "0", "AN", "Value must be a recordset", null)]
        [NUnit.Framework.TestCaseAttribute("Test", "0", "AN", "Value must be a recordset", null)]
        [NUnit.Framework.TestCaseAttribute("99", "0", "AN", "Value must be a recordset", null)]
        [NUnit.Framework.TestCaseAttribute("[[rs([[var]])]]", "0", "AN", "[[result]] = Error", null)]
        public virtual void EnsureVariablesOfDifferentTypesProduceDesiredResults(string count, string val, string error, string message, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Ensure variables of different types produce desired results", exampleTags);
#line 180
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1775 = new TechTalk.SpecFlow.Table(new string[] {
                        "[[rs]]",
                        ""});
            table1775.AddRow(new string[] {
                        "rs().row",
                        "1"});
            table1775.AddRow(new string[] {
                        "rs().row",
                        "2"});
            table1775.AddRow(new string[] {
                        "rs().row",
                        "3"});
#line 181
 testRunner.Given("I have a recordset with this shape", ((string)(null)), table1775, "Given ");
#line 186
 testRunner.And("count on record \"<count>\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 187
 testRunner.When("the count tool is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 188
 testRunner.Then(string.Format("the result count should be \"{0}\"", val), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 189
 testRunner.And(string.Format("the execution has \"{0}\" error", error), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
