// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Warewolf.Tools.Specs.Toolbox.Utility.DateandTime
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Aggregated Calculation")]
    [NUnit.Framework.CategoryAttribute("Utility")]
    public partial class AggregatedCalculationFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "DateandTime.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Aggregated Calculation", "\tIn order to perform aggrgate calculations\r\n\tAs a Warewolf user\r\n\tI want a tool t" +
                    "hat I can input a formula and will calculate and retun a result", ProgrammingLanguage.CSharp, new string[] {
                        "Utility"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Aggregated Calculation using a given formula")]
        public virtual void AggregatedCalculationUsingAGivenFormula()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Aggregated Calculation using a given formula", ((string[])(null)));
#line 23
this.ScenarioSetup(scenarioInfo);
#line 24
 testRunner.Given("I have the formula \"mod(sqrt(49), 7)\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 25
 testRunner.When("the aggregate calculate tool is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 26
 testRunner.Then("the calculate result should be \"0\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 27
 testRunner.And("the execution has \"NO\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1694 = new TechTalk.SpecFlow.Table(new string[] {
                        "fx ="});
            table1694.AddRow(new string[] {
                        "mod(sqrt(49), 7)"});
#line 28
 testRunner.And("the debug inputs as", ((string)(null)), table1694, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1695 = new TechTalk.SpecFlow.Table(new string[] {
                        ""});
            table1695.AddRow(new string[] {
                        "[[result]] = 0"});
#line 31
 testRunner.And("the debug output as", ((string)(null)), table1695, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Aggregated Calculation using multiple scalars and recordset inputs")]
        public virtual void AggregatedCalculationUsingMultipleScalarsAndRecordsetInputs()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Aggregated Calculation using multiple scalars and recordset inputs", ((string[])(null)));
#line 35
this.ScenarioSetup(scenarioInfo);
#line 36
 testRunner.Given("I have a calculate variable \"[[var]]\" equal to \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 37
 testRunner.And("I have a calculate variable \"[[var2]]\" equal to \"20\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 38
 testRunner.And("I have the formula \"((([[var]]+[[var]])/[[var2]])+[[var2]]*[[var]])\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 39
 testRunner.When("the aggregate calculate tool is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 40
 testRunner.Then("the calculate result should be \"20.1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 41
 testRunner.And("the execution has \"NO\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1696 = new TechTalk.SpecFlow.Table(new string[] {
                        "fx ="});
            table1696.AddRow(new string[] {
                        "((([[var]]+[[var]])/[[var2]])+[[var2]]*[[var]]) = (((1+1)/20)+20*1)"});
#line 42
 testRunner.And("the debug inputs as", ((string)(null)), table1696, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1697 = new TechTalk.SpecFlow.Table(new string[] {
                        ""});
            table1697.AddRow(new string[] {
                        "[[result]] = 20.1"});
#line 45
 testRunner.And("the debug output as", ((string)(null)), table1697, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Aggregated Calculation with new lines should concatenate values")]
        public virtual void AggregatedCalculationWithNewLinesShouldConcatenateValues()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Aggregated Calculation with new lines should concatenate values", ((string[])(null)));
#line 49
this.ScenarioSetup(scenarioInfo);
#line 50
 testRunner.Given("I have a calculate variable \"[[var]]\" equal to \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 51
 testRunner.And("I have a calculate variable \"[[var2]]\" equal to \"20\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 52
 testRunner.And("I have the formula \"[[var]]\\r\\n[[var2]]\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 53
 testRunner.When("the aggregate calculate tool is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 54
 testRunner.Then("the calculate result should be \"120\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 55
 testRunner.And("the execution has \"NO\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1698 = new TechTalk.SpecFlow.Table(new string[] {
                        "fx ="});
            table1698.AddRow(new string[] {
                        "String = String"});
#line 56
 testRunner.And("the debug inputs as", ((string)(null)), table1698, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1699 = new TechTalk.SpecFlow.Table(new string[] {
                        ""});
            table1699.AddRow(new string[] {
                        "[[result]] = 120"});
#line 59
 testRunner.And("the debug output as", ((string)(null)), table1699, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Aggregated Calculation using Recordset (*) input in an agregate function like SUM" +
            "")]
        public virtual void AggregatedCalculationUsingRecordsetInputInAnAgregateFunctionLikeSUM()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Aggregated Calculation using Recordset (*) input in an agregate function like SUM" +
                    "", ((string[])(null)));
#line 63
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1700 = new TechTalk.SpecFlow.Table(new string[] {
                        "var().int"});
            table1700.AddRow(new string[] {
                        "1"});
            table1700.AddRow(new string[] {
                        "2"});
            table1700.AddRow(new string[] {
                        "3"});
#line 64
 testRunner.Given("I have a calculate variable \"[[var().int]]\" equal to", ((string)(null)), table1700, "Given ");
#line 69
 testRunner.And("I have the formula \"SUM([[var(*).int]])\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 70
 testRunner.When("the aggregate calculate tool is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 71
 testRunner.Then("the calculate result should be \"6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 72
 testRunner.And("the execution has \"NO\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1701 = new TechTalk.SpecFlow.Table(new string[] {
                        "fx ="});
            table1701.AddRow(new string[] {
                        "SUM([[var(*).int]]) = SUM(1,2,3)"});
#line 73
 testRunner.And("the debug inputs as", ((string)(null)), table1701, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1702 = new TechTalk.SpecFlow.Table(new string[] {
                        ""});
            table1702.AddRow(new string[] {
                        "[[result]] = 6"});
#line 76
 testRunner.And("the debug output as", ((string)(null)), table1702, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Aggregated Calculation using Recordset (*) input in an agregate function like SUM" +
            " and output recordset star")]
        public virtual void AggregatedCalculationUsingRecordsetInputInAnAgregateFunctionLikeSUMAndOutputRecordsetStar()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Aggregated Calculation using Recordset (*) input in an agregate function like SUM" +
                    " and output recordset star", ((string[])(null)));
#line 80
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1703 = new TechTalk.SpecFlow.Table(new string[] {
                        "var().int"});
            table1703.AddRow(new string[] {
                        "1"});
            table1703.AddRow(new string[] {
                        "2"});
            table1703.AddRow(new string[] {
                        "3"});
#line 81
 testRunner.Given("I have a calculate variable \"[[var().int]]\" equal to", ((string)(null)), table1703, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1704 = new TechTalk.SpecFlow.Table(new string[] {
                        "rs().val"});
            table1704.AddRow(new string[] {
                        "10"});
            table1704.AddRow(new string[] {
                        "23"});
#line 86
 testRunner.And("I have a calculate variable \"[[rs().val]]\" equal to", ((string)(null)), table1704, "And ");
#line 90
 testRunner.And("I have the formula \"SUM([[var(*).int]])\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 91
 testRunner.And("calculate result as \"[[rs(*).val]]\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 92
 testRunner.When("the aggregate calculate tool is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 93
 testRunner.Then("the execution has \"NO\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table1705 = new TechTalk.SpecFlow.Table(new string[] {
                        "fx ="});
            table1705.AddRow(new string[] {
                        "SUM([[var(*).int]]) = SUM(1,2,3)"});
#line 94
 testRunner.And("the debug inputs as", ((string)(null)), table1705, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1706 = new TechTalk.SpecFlow.Table(new string[] {
                        ""});
            table1706.AddRow(new string[] {
                        "[[rs(1).val]] = 6"});
            table1706.AddRow(new string[] {
                        "[[rs(2).val]] = 23"});
#line 97
 testRunner.And("the debug output as", ((string)(null)), table1706, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Aggregated Calculation using Recordset (*) input in an agregate function like SUM" +
            " and output recordset star complex")]
        public virtual void AggregatedCalculationUsingRecordsetInputInAnAgregateFunctionLikeSUMAndOutputRecordsetStarComplex()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Aggregated Calculation using Recordset (*) input in an agregate function like SUM" +
                    " and output recordset star complex", ((string[])(null)));
#line 102
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1707 = new TechTalk.SpecFlow.Table(new string[] {
                        "var().int"});
            table1707.AddRow(new string[] {
                        "1"});
            table1707.AddRow(new string[] {
                        "2"});
            table1707.AddRow(new string[] {
                        "3"});
#line 103
 testRunner.Given("I have a calculate variable \"[[var().int]]\" equal to", ((string)(null)), table1707, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1708 = new TechTalk.SpecFlow.Table(new string[] {
                        "rs().val"});
            table1708.AddRow(new string[] {
                        "10"});
            table1708.AddRow(new string[] {
                        "23"});
#line 108
 testRunner.And("I have a calculate variable \"[[rs().val]]\" equal to", ((string)(null)), table1708, "And ");
#line 112
 testRunner.And("I have the formula \"SUM([[var(*).int]]) + 15\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 113
 testRunner.And("calculate result as \"[[rs(*).val]]\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 114
 testRunner.When("the aggregate calculate tool is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 115
 testRunner.Then("the execution has \"NO\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table1709 = new TechTalk.SpecFlow.Table(new string[] {
                        "fx ="});
            table1709.AddRow(new string[] {
                        "SUM([[var(*).int]]) + 15 = SUM(1,2,3)+15"});
#line 116
 testRunner.And("the debug inputs as", ((string)(null)), table1709, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1710 = new TechTalk.SpecFlow.Table(new string[] {
                        ""});
            table1710.AddRow(new string[] {
                        "[[rs(1).val]] = 21"});
            table1710.AddRow(new string[] {
                        "[[rs(2).val]] = 23"});
#line 119
 testRunner.And("the debug output as", ((string)(null)), table1710, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Aggregated Calculation using incorrect formula")]
        public virtual void AggregatedCalculationUsingIncorrectFormula()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Aggregated Calculation using incorrect formula", ((string[])(null)));
#line 124
this.ScenarioSetup(scenarioInfo);
#line 125
 testRunner.Given("I have the formula \"asdf\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 126
 testRunner.When("the aggregate calculate tool is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 127
 testRunner.Then("the calculate result should be \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 128
 testRunner.And("the execution has \"Formula syntax error. Unable to compile the formula: Unexpecte" +
                    "d end of file, on line: 1 column: 5\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1711 = new TechTalk.SpecFlow.Table(new string[] {
                        "fx ="});
            table1711.AddRow(new string[] {
                        "asdf"});
#line 129
 testRunner.And("the debug inputs as", ((string)(null)), table1711, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1712 = new TechTalk.SpecFlow.Table(new string[] {
                        ""});
            table1712.AddRow(new string[] {
                        "[[result]] ="});
#line 132
 testRunner.And("the debug output as", ((string)(null)), table1712, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Aggregated Calculation using variable as full calculation")]
        public virtual void AggregatedCalculationUsingVariableAsFullCalculation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Aggregated Calculation using variable as full calculation", ((string[])(null)));
#line 137
this.ScenarioSetup(scenarioInfo);
#line 138
 testRunner.Given("I have a calculate variable \"[[var]]\" equal to \"SUM(1,2,3)-5\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 139
 testRunner.And("I have the formula \"[[var]]\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 140
 testRunner.When("the aggregate calculate tool is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 141
 testRunner.Then("the calculate result should be \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 142
 testRunner.And("the execution has \"NO\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1713 = new TechTalk.SpecFlow.Table(new string[] {
                        "fx ="});
            table1713.AddRow(new string[] {
                        "[[var]] =  SUM(1,2,3)-5"});
#line 143
 testRunner.And("the debug inputs as", ((string)(null)), table1713, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1714 = new TechTalk.SpecFlow.Table(new string[] {
                        ""});
            table1714.AddRow(new string[] {
                        "[[result]] = 1"});
#line 146
 testRunner.And("the debug output as", ((string)(null)), table1714, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Aggregated Calculation using a negative index recordset value")]
        public virtual void AggregatedCalculationUsingANegativeIndexRecordsetValue()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Aggregated Calculation using a negative index recordset value", ((string[])(null)));
#line 150
this.ScenarioSetup(scenarioInfo);
#line 151
 testRunner.Given("I have the formula \"[[my(-1).formula]]\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 152
 testRunner.When("the aggregate calculate tool is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 153
 testRunner.Then("the execution has \"Recordset index [ -1 ] is not greater than zero\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table1715 = new TechTalk.SpecFlow.Table(new string[] {
                        "fx ="});
            table1715.AddRow(new string[] {
                        "[[my(-1).formula]] ="});
#line 154
 testRunner.And("the debug inputs as", ((string)(null)), table1715, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1716 = new TechTalk.SpecFlow.Table(new string[] {
                        ""});
            table1716.AddRow(new string[] {
                        "[[result]] ="});
#line 157
 testRunner.And("the debug output as", ((string)(null)), table1716, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Aggregated Calculation using isnumber and blank")]
        public virtual void AggregatedCalculationUsingIsnumberAndBlank()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Aggregated Calculation using isnumber and blank", ((string[])(null)));
#line 161
this.ScenarioSetup(scenarioInfo);
#line 162
    testRunner.Given("I have the formula \"if(isnumber(\"\"),\"Is number\",\"Not number\")\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 163
 testRunner.When("the calculate tool is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 164
 testRunner.Then("the calculate result should be \"Not number\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table1717 = new TechTalk.SpecFlow.Table(new string[] {
                        "fx ="});
            table1717.AddRow(new string[] {
                        "\"if(isnumber(\"\"),\"Is number\",\"Not number\")\""});
#line 165
 testRunner.And("the debug inputs as", ((string)(null)), table1717, "And ");
#line 168
 testRunner.And("the execution has \"NO\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Aggregated Calculation Assign by evaluating a variable inside a variable")]
        public virtual void AggregatedCalculationAssignByEvaluatingAVariableInsideAVariable()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Aggregated Calculation Assign by evaluating a variable inside a variable", ((string[])(null)));
#line 171
this.ScenarioSetup(scenarioInfo);
#line 172
 testRunner.Given("I have a calculate variable \"[[a]]\" equal to \"b\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 173
 testRunner.And("I have a calculate variable \"[[b]]\" equal to \"20\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 174
 testRunner.And("I have the formula \"[[[[a]]]]+1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 175
 testRunner.When("the aggregate calculate tool is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 176
 testRunner.Then("the calculate result should be \"21\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 177
 testRunner.And("the execution has \"NO\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1718 = new TechTalk.SpecFlow.Table(new string[] {
                        "fx ="});
            table1718.AddRow(new string[] {
                        "[[b]]+1 = 20+1"});
#line 178
 testRunner.And("the debug inputs as", ((string)(null)), table1718, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1719 = new TechTalk.SpecFlow.Table(new string[] {
                        ""});
            table1719.AddRow(new string[] {
                        "[[result]] = 21"});
#line 181
 testRunner.And("the debug output as", ((string)(null)), table1719, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Aggregated Calculation Assign by evaluating a variable inside a variable with fun" +
            "ction")]
        public virtual void AggregatedCalculationAssignByEvaluatingAVariableInsideAVariableWithFunction()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Aggregated Calculation Assign by evaluating a variable inside a variable with fun" +
                    "ction", ((string[])(null)));
#line 185
this.ScenarioSetup(scenarioInfo);
#line 186
 testRunner.Given("I have a calculate variable \"[[a]]\" equal to \"b\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 187
 testRunner.And("I have a calculate variable \"[[b]]\" equal to \"20\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 188
 testRunner.And("I have the formula \"SUM([[[[a]]]],[[b]])\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 189
 testRunner.When("the aggregate calculate tool is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 190
 testRunner.Then("the calculate result should be \"40\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 191
 testRunner.And("the execution has \"NO\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1720 = new TechTalk.SpecFlow.Table(new string[] {
                        "fx ="});
            table1720.AddRow(new string[] {
                        "SUM([[b]],20) = SUM(20,20)"});
#line 192
 testRunner.And("the debug inputs as", ((string)(null)), table1720, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1721 = new TechTalk.SpecFlow.Table(new string[] {
                        ""});
            table1721.AddRow(new string[] {
                        "[[result]] = 40"});
#line 195
 testRunner.And("the debug output as", ((string)(null)), table1721, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Aggregated Calculation Assign by evaluating variables with functions")]
        [NUnit.Framework.TestCaseAttribute("1", "abs([[e]])", "1000", null)]
        [NUnit.Framework.TestCaseAttribute("2", "acos([[x]])", "0", null)]
        [NUnit.Framework.TestCaseAttribute("3", "acosh([[rc(1).set]])", "2.29243166956118", null)]
        [NUnit.Framework.TestCaseAttribute("4", "AND([[s]]<[[z]]<5)", "False", null)]
        [NUnit.Framework.TestCaseAttribute("5", "AND([[y]]<5)", "True", null)]
        [NUnit.Framework.TestCaseAttribute("7", "ASIN([[s]])", "-1.57079632679490", null)]
        [NUnit.Framework.TestCaseAttribute("8", "ASINH([[rc(1).set]])", "2.312438341272750", null)]
        [NUnit.Framework.TestCaseAttribute("9", "ATAN([[s]])", "-0.785398163397448", null)]
        [NUnit.Framework.TestCaseAttribute("10", "ATAN2([[x]],[[s]])", "-0.785398163397448", null)]
        [NUnit.Framework.TestCaseAttribute("11", "ATANH([[t]])", "0", null)]
        [NUnit.Framework.TestCaseAttribute("12", "AVEDEV([[x]],[[z]])", "4.5", null)]
        [NUnit.Framework.TestCaseAttribute("13", "AVERAGE([[x]],[[y]],[[z]],[[rc(1).set]],[[s]],[[t]],[[e]])", "145.285714285714", null)]
        [NUnit.Framework.TestCaseAttribute("14", "BIN2DEC([[z]])", "2", null)]
        [NUnit.Framework.TestCaseAttribute("15", "BIN2HEX([[x]])", "1", null)]
        [NUnit.Framework.TestCaseAttribute("16", "BIN2OCT([[z]])", "2", null)]
        [NUnit.Framework.TestCaseAttribute("17", "CEILING([[z]],[[y]])", "10", null)]
        [NUnit.Framework.TestCaseAttribute("18", "char([[x]][[t]][[x]])", "e", null)]
        [NUnit.Framework.TestCaseAttribute("19", "CHOOSE(4,[[z]],[[t]],[[rc(1).set]],100)", "100", null)]
        [NUnit.Framework.TestCaseAttribute("20", "CODE(111)", "49", null)]
        [NUnit.Framework.TestCaseAttribute("21", "COMBIN([[z]],[[y]])", "45", null)]
        [NUnit.Framework.TestCaseAttribute("22", "COMPLEX([[y]],[[e]])", "2+1000i", null)]
        [NUnit.Framework.TestCaseAttribute("23", "CONCATENATE([[z]],[[x]])", "101", null)]
        [NUnit.Framework.TestCaseAttribute("24", "CONVERT([[z]],\"m\",\"in\")", "393.700787401575", null)]
        [NUnit.Framework.TestCaseAttribute("25", "COS([[[[a]]]])", "-0.989992496600445", null)]
        [NUnit.Framework.TestCaseAttribute("26", "COSH([[z]])", "11013.232920103300", null)]
        [NUnit.Framework.TestCaseAttribute("27", "COUNT([[x]],[[y]],[[[[a]]]])", "3", null)]
        [NUnit.Framework.TestCaseAttribute("29", "DATE(2000,[[y]],12)", "{2/12/2000 12:00:00.000 AM} or {12/02/2000 12:00:00.000 AM}", null)]
        [NUnit.Framework.TestCaseAttribute("30", "DAY([[x]])", "1", null)]
        [NUnit.Framework.TestCaseAttribute("31", "DAYS360([[x]],[[y]])", "1", null)]
        [NUnit.Framework.TestCaseAttribute("32", "DB([[e]],[[z]],12,12,12)", "4.66024676978963", null)]
        [NUnit.Framework.TestCaseAttribute("33", "DBNull()", "", null)]
        [NUnit.Framework.TestCaseAttribute("34", "DDB([[e]],[[z]],12,12,[[x]])", "31.9996025467397", null)]
        [NUnit.Framework.TestCaseAttribute("35", "DEC2BIN([[x]],[[z]])", "0000000001", null)]
        [NUnit.Framework.TestCaseAttribute("36", "DEC2HEX(1,10)", "0000000001", null)]
        [NUnit.Framework.TestCaseAttribute("37", "DEC2OCT([[y]],[[z]])", "0000000002", null)]
        [NUnit.Framework.TestCaseAttribute("38", "DEGREES([[z]])", "572.957795130823", null)]
        [NUnit.Framework.TestCaseAttribute("39", "DELTA([[t]],[[x]])", "0", null)]
        [NUnit.Framework.TestCaseAttribute("40", "DOLLARDE([[z]],[[y]])", "10", null)]
        [NUnit.Framework.TestCaseAttribute("41", "DOLLARFR([[x]],[[z]])", "1", null)]
        [NUnit.Framework.TestCaseAttribute("42", "EDATE([[z]],[[[[a]]]])", "{4/10/1900 12:00:00.000 AM} or {10/04/1900 12:00:00.000 AM}", null)]
        [NUnit.Framework.TestCaseAttribute("43", "EOMONTH([[z]],[[[[a]]]])", "{4/30/1900 12:00:00.000 AM} or {30/04/1900 12:00:00.000 AM}", null)]
        [NUnit.Framework.TestCaseAttribute("45", "EVEN([[y]])", "2", null)]
        [NUnit.Framework.TestCaseAttribute("46", "EXP([[x]])", "2.71828182845905", null)]
        [NUnit.Framework.TestCaseAttribute("47", "FACT([[z]])", "3628800", null)]
        [NUnit.Framework.TestCaseAttribute("48", "FIND([[t]],[[e]])", "2", null)]
        [NUnit.Framework.TestCaseAttribute("49", "FACTDOUBLE([[z]])", "3840", null)]
        [NUnit.Framework.TestCaseAttribute("50", "FLOOR([[z]],[[z]])", "10", null)]
        [NUnit.Framework.TestCaseAttribute("51", "FV(10,12,100,10,1)", "-376611405206410", null)]
        [NUnit.Framework.TestCaseAttribute("52", "GCD([[x]],[[z]])", "1", null)]
        [NUnit.Framework.TestCaseAttribute("53", "GESTEP([[[[a]]]],[[s]])", "1", null)]
        [NUnit.Framework.TestCaseAttribute("54", "HEX2BIN([[y]],[[y]])", "10", null)]
        [NUnit.Framework.TestCaseAttribute("55", "HEX2DEC([[rc(1).set]])", "5", null)]
        [NUnit.Framework.TestCaseAttribute("56", "HEX2OCT([[rc(1).set]])", "5", null)]
        [NUnit.Framework.TestCaseAttribute("57", "IF([[z]],[[rc(1).set]])", "5", null)]
        [NUnit.Framework.TestCaseAttribute("58", "IFERROR([[t]],[[x]])", "0", null)]
        [NUnit.Framework.TestCaseAttribute("59", "IMABS([[x]])", "1", null)]
        [NUnit.Framework.TestCaseAttribute("60", "IMAGINARY([[rc(1).set]])", "0", null)]
        [NUnit.Framework.TestCaseAttribute("61", "IMARGUMENT([[e]])", "0", null)]
        [NUnit.Framework.TestCaseAttribute("62", "IMCONJUGATE([[[[a]]]])", "3", null)]
        [NUnit.Framework.TestCaseAttribute("63", "IMCOS([[y]])", "-0.416146836547142", null)]
        [NUnit.Framework.TestCaseAttribute("64", "IMDIV(1,10)", "0.1", null)]
        [NUnit.Framework.TestCaseAttribute("65", "IMEXP([[rc(1).set]])", "148.413159102577", null)]
        [NUnit.Framework.TestCaseAttribute("66", "IMLN([[[[a]]]])", "1.09861228866811", null)]
        [NUnit.Framework.TestCaseAttribute("67", "IMLOG10([[y]])", "0.301029995663981", null)]
        [NUnit.Framework.TestCaseAttribute("68", "IMLOG2([[y]])", "1", null)]
        [NUnit.Framework.TestCaseAttribute("69", "IMPOWER(2,[[z]])", "1024", null)]
        [NUnit.Framework.TestCaseAttribute("70", "IMPRODUCT([[x]],[[y]])", "2", null)]
        [NUnit.Framework.TestCaseAttribute("71", "IMREAL([[z]])", "10", null)]
        [NUnit.Framework.TestCaseAttribute("72", "IMSIN([[x]])", "0.841470984807897", null)]
        [NUnit.Framework.TestCaseAttribute("73", "IMSQRT([[e]])", "31.6227766016838", null)]
        [NUnit.Framework.TestCaseAttribute("74", "IMSUB([[x]],[[rc(1).set]])", "-4", null)]
        [NUnit.Framework.TestCaseAttribute("75", "IMSUM([[x]],[[rc(1).set]])", "6", null)]
        [NUnit.Framework.TestCaseAttribute("77", "INT([[s]])", "-1", null)]
        [NUnit.Framework.TestCaseAttribute("78", "INTRATE(2015,2030,1000,1,4)", "-23.976", null)]
        [NUnit.Framework.TestCaseAttribute("79", "IPMT(5,12,100,1000,2000,1)", "-833.333358764648", null)]
        [NUnit.Framework.TestCaseAttribute("81", "isdbnull([[x]])", "False", null)]
        [NUnit.Framework.TestCaseAttribute("82", "ISBLANK(1)", "False", null)]
        [NUnit.Framework.TestCaseAttribute("83", "ISERR([[e]])", "False", null)]
        [NUnit.Framework.TestCaseAttribute("84", "ISERROR([[rc(1).set]])", "False", null)]
        [NUnit.Framework.TestCaseAttribute("85", "ISEVEN([[z]])", "True", null)]
        [NUnit.Framework.TestCaseAttribute("86", "ISLOGICAL([[x]])", "False", null)]
        [NUnit.Framework.TestCaseAttribute("87", "ISNA([[t]])", "False", null)]
        [NUnit.Framework.TestCaseAttribute("88", "ISNONTEXT([[[[a]]]])", "True", null)]
        [NUnit.Framework.TestCaseAttribute("89", "ISNUMBER([[x]])", "True", null)]
        [NUnit.Framework.TestCaseAttribute("90", "ISODD([[[[a]]]])", "True", null)]
        [NUnit.Framework.TestCaseAttribute("91", "ISREF([[t]])", "False", null)]
        [NUnit.Framework.TestCaseAttribute("92", "ISTEXT([[rc(1).set]])", "False", null)]
        [NUnit.Framework.TestCaseAttribute("93", "LCM(1,2,10)", "10", null)]
        [NUnit.Framework.TestCaseAttribute("94", "LEFT([[x]],[[e]])", "1", null)]
        [NUnit.Framework.TestCaseAttribute("95", "LEN([[z]])", "2", null)]
        [NUnit.Framework.TestCaseAttribute("96", "LN([[rc(1).set]])", "1.6094379124341", null)]
        [NUnit.Framework.TestCaseAttribute("97", "LOG([[z]],[[y]])", "3.32192809488736", null)]
        [NUnit.Framework.TestCaseAttribute("98", "LOG10([[z]])", "1", null)]
        [NUnit.Framework.TestCaseAttribute("99", "LOWER([[rc(1).set]])", "5", null)]
        [NUnit.Framework.TestCaseAttribute("100", "MAX(10,1,1000)", "1000", null)]
        [NUnit.Framework.TestCaseAttribute("101", "MEDIAN(10,1,1000)", "10", null)]
        [NUnit.Framework.TestCaseAttribute("102", "MID(10,1,1000)", "10", null)]
        [NUnit.Framework.TestCaseAttribute("103", "MIN(10,1,1000)", "1", null)]
        [NUnit.Framework.TestCaseAttribute("104", "MINUTE([[[[a]]]])", "0", null)]
        [NUnit.Framework.TestCaseAttribute("105", "MOD([[b]],[[rc(1).set]])", "3", null)]
        [NUnit.Framework.TestCaseAttribute("106", "MONTH([[z]])", "1", null)]
        [NUnit.Framework.TestCaseAttribute("107", "MROUND([[x]],[[y]])", "2", null)]
        [NUnit.Framework.TestCaseAttribute("108", "MULTINOMIAL(10,[[x]],2)", "858", null)]
        [NUnit.Framework.TestCaseAttribute("109", "N([[s]])", "-1", null)]
        [NUnit.Framework.TestCaseAttribute("111", "NETWORKDAYS(2014,2015)", "2", null)]
        [NUnit.Framework.TestCaseAttribute("112", "NOT([[[[a]]]])", "False", null)]
        [NUnit.Framework.TestCaseAttribute("113", "NOW()", "[Now]", null)]
        [NUnit.Framework.TestCaseAttribute("114", "NPER(0.1, 100, 1000, 999,0)", "-79.74911468163210", null)]
        [NUnit.Framework.TestCaseAttribute("115", "NPV([[z]],[[z]],[[rc(1).set]],[[y]])", "0.951915852742299", null)]
        [NUnit.Framework.TestCaseAttribute("117", "OCT2BIN([[z]],[[z]])", "0000001000", null)]
        [NUnit.Framework.TestCaseAttribute("118", "OCT2DEC([[z]])", "8", null)]
        [NUnit.Framework.TestCaseAttribute("119", "OCT2HEX(10,2)", "08", null)]
        [NUnit.Framework.TestCaseAttribute("120", "ODD([[z]])", "11", null)]
        [NUnit.Framework.TestCaseAttribute("121", "OR(1,2)", "True", null)]
        [NUnit.Framework.TestCaseAttribute("122", "PI()", "3.14159265358979", null)]
        [NUnit.Framework.TestCaseAttribute("123", "PMT([[z]],[[x]],100,200,[[t]])", "-1300", null)]
        [NUnit.Framework.TestCaseAttribute("124", "POWER([[z]],[[y]])", "100", null)]
        [NUnit.Framework.TestCaseAttribute("125", "PPMT(10,1,1,1000,500,0)", "-1500", null)]
        [NUnit.Framework.TestCaseAttribute("126", "PRODUCT([[x]],[[y]],[[z]])", "20", null)]
        [NUnit.Framework.TestCaseAttribute("127", "PV(5,1,10,100,0)", "-18.3333333333333", null)]
        [NUnit.Framework.TestCaseAttribute("128", "QUOTIENT([[z]],[[rc(1).set]])", "2", null)]
        [NUnit.Framework.TestCaseAttribute("129", "RADIANS([[z]])", "0.174532925199433", null)]
        [NUnit.Framework.TestCaseAttribute("130", "RANDBETWEEN([[x]],10)", "[Int]", null)]
        [NUnit.Framework.TestCaseAttribute("131", "RATE(360,-600,100000,0,1)", "0.00504500404584643", null)]
        [NUnit.Framework.TestCaseAttribute("132", "REPT([[y]],[[y]])", "22", null)]
        [NUnit.Framework.TestCaseAttribute("133", "RIGHT([[x]],[[x]])", "1", null)]
        [NUnit.Framework.TestCaseAttribute("134", "ROMAN(10,0)", "X", null)]
        [NUnit.Framework.TestCaseAttribute("135", "ROUND([[rc(1).set]],3)", "5", null)]
        [NUnit.Framework.TestCaseAttribute("136", "ROUNDDOWN([[rc(1).set]],3)", "5", null)]
        [NUnit.Framework.TestCaseAttribute("137", "ROUNDUP(5,2)", "5", null)]
        [NUnit.Framework.TestCaseAttribute("138", "SEARCH(1,[[x]],1)", "1", null)]
        [NUnit.Framework.TestCaseAttribute("139", "SEARCHB(1,1,1)", "1", null)]
        [NUnit.Framework.TestCaseAttribute("140", "SECOND([[e]])", "0", null)]
        [NUnit.Framework.TestCaseAttribute("141", "SERIESSUM(1000,10,10,10)", "1E+31", null)]
        [NUnit.Framework.TestCaseAttribute("142", "SIGN(50)", "1", null)]
        [NUnit.Framework.TestCaseAttribute("143", "SIN([[z]])", "-0.54402111088937", null)]
        [NUnit.Framework.TestCaseAttribute("144", "SINH([[z]])", "11013.2328747034", null)]
        [NUnit.Framework.TestCaseAttribute("145", "SLN(100,10,[[x]])", "90", null)]
        [NUnit.Framework.TestCaseAttribute("146", "SQRT(16)", "4", null)]
        [NUnit.Framework.TestCaseAttribute("147", "SQRTPI(16)", "7.08981540362206", null)]
        [NUnit.Framework.TestCaseAttribute("148", "STDEV(1,10,5)", "4.50924975282289", null)]
        [NUnit.Framework.TestCaseAttribute("149", "SUBTOTAL(2,[[x]],[[z]],0)", "3", null)]
        [NUnit.Framework.TestCaseAttribute("150", "SUM([[rc(1).set]],[[z]],[[s]])", "14", null)]
        [NUnit.Framework.TestCaseAttribute("151", "SYD(1000,[[z]],[[rc(1).set]],[[x]])", "330", null)]
        [NUnit.Framework.TestCaseAttribute("152", "TAN([[z]])", "0.648360827459087", null)]
        [NUnit.Framework.TestCaseAttribute("153", "TANH([[z]])", "0.999999995877693", null)]
        [NUnit.Framework.TestCaseAttribute("154", "TEXT([[y]],[[rc(1).set]])", "5", null)]
        [NUnit.Framework.TestCaseAttribute("155", "TIME(24,[[x]],[[x]])", "0.000706018518518518", null)]
        [NUnit.Framework.TestCaseAttribute("156", "TIMEVALUE(\"2:24 AM\")", "0.1", null)]
        [NUnit.Framework.TestCaseAttribute("157", "TODAY()", "[Today]", null)]
        [NUnit.Framework.TestCaseAttribute("158", "TRIM(10)", "10", null)]
        [NUnit.Framework.TestCaseAttribute("159", "TRUNC(1000,[[rc(1).set]])", "1000", null)]
        [NUnit.Framework.TestCaseAttribute("160", "TYPE(-1)", "1", null)]
        [NUnit.Framework.TestCaseAttribute("161", "UPPER(-1)", "-1", null)]
        [NUnit.Framework.TestCaseAttribute("162", "VALUE([[x]])", "1", null)]
        [NUnit.Framework.TestCaseAttribute("163", "VAR([[rc(1).set]],[[z]])", "12.5", null)]
        [NUnit.Framework.TestCaseAttribute("164", "WEEKDAY(11011,[[x]])", "7", null)]
        [NUnit.Framework.TestCaseAttribute("165", "WEEKNUM(11011,[[y]])", "8", null)]
        [NUnit.Framework.TestCaseAttribute("166", "WORKDAY([[rc(1).set]],[[rc(1).set]],[[z]])", "{1/15/1900 12:00:00.000 AM} or {15/01/1900 12:00:00.000 AM}", null)]
        [NUnit.Framework.TestCaseAttribute("167", "YEAR(11011)", "1930", null)]
        public virtual void AggregatedCalculationAssignByEvaluatingVariablesWithFunctions(string no, string fx, string result, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Aggregated Calculation Assign by evaluating variables with functions", exampleTags);
#line 199
this.ScenarioSetup(scenarioInfo);
#line 200
 testRunner.Given("I have a calculate variable \"[[x]]\" equal to \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 201
 testRunner.And("I have a calculate variable \"[[y]]\" equal to \"2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 202
 testRunner.And("I have a calculate variable \"[[z]]\" equal to \"10\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 203
 testRunner.And("I have a calculate variable \"[[rc(1).set]]\" equal to \"5\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 204
 testRunner.And("I have a calculate variable \"[[s]]\" equal to \"-1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 205
 testRunner.And("I have a calculate variable \"[[t]]\" equal to \"0\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 206
 testRunner.And("I have a calculate variable \"[[a]]\" equal to \"b\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 207
 testRunner.And("I have a calculate variable \"[[b]]\" equal to \"3\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 208
 testRunner.And("I have a calculate variable \"[[e]]\" equal to \"1000\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 209
 testRunner.And(string.Format("I have the Example formula \"{0}\"", fx), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 210
 testRunner.And("The system short date format is \"dd/MM/yyyy\" and the long time format is \"hh:mm:s" +
                    "s tt\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 211
 testRunner.When("the aggregate calculate tool is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 212
 testRunner.Then(string.Format("the calculate result should be \"{0}\"", result), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 213
 testRunner.And("the execution has \"NO\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Calculate using Recordset input in an agregate function like SUM")]
        [NUnit.Framework.TestCaseAttribute("1", "SUM([[var([[val]]).int]])", "3", null)]
        [NUnit.Framework.TestCaseAttribute("2", "SUM([[var([[val]]).int]],[[var([[val]]).int]])", "6", null)]
        [NUnit.Framework.TestCaseAttribute("3", "SUM([[var([[val]]).int]],[[var([[val]]).int]])", "6", null)]
        public virtual void CalculateUsingRecordsetInputInAnAgregateFunctionLikeSUM(string no, string fx, string value, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Calculate using Recordset input in an agregate function like SUM", exampleTags);
#line 377
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1722 = new TechTalk.SpecFlow.Table(new string[] {
                        "var().int"});
            table1722.AddRow(new string[] {
                        "1"});
            table1722.AddRow(new string[] {
                        "2"});
            table1722.AddRow(new string[] {
                        "3"});
#line 378
 testRunner.Given("I have a calculate variable \"[[var().int]]\" equal to", ((string)(null)), table1722, "Given ");
#line 383
 testRunner.And("I have a calculate variable \"[[val]]\" equal to \"3\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 384
 testRunner.And(string.Format("I have the formula \"{0}\"", fx), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 385
 testRunner.When("the aggregate calculate tool is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 386
 testRunner.Then(string.Format("the calculate result should be \"{0}\"", value), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 387
 testRunner.And("the execution has \"NO\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Aggregated Calculation using variables with a null value")]
        public virtual void AggregatedCalculationUsingVariablesWithANullValue()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Aggregated Calculation using variables with a null value", ((string[])(null)));
#line 394
this.ScenarioSetup(scenarioInfo);
#line 395
 testRunner.Given("I have a calculate variable \"[[a]]\" equal to \"NULL\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 396
 testRunner.And("I have a calculate variable \"[[b]]\" equal to \"NULL\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 397
 testRunner.And("I have the formula \"SUM([[a]],[[b]])\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 398
 testRunner.When("the aggregate calculate tool is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 399
 testRunner.Then("the execution has \"An\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table1723 = new TechTalk.SpecFlow.Table(new string[] {
                        "fx ="});
            table1723.AddRow(new string[] {
                        "SUM([[a]],[[b]]) = SUM(,)"});
#line 400
 testRunner.And("the debug inputs as", ((string)(null)), table1723, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Variable that does not exist")]
        public virtual void VariableThatDoesNotExist()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Variable that does not exist", ((string[])(null)));
#line 404
this.ScenarioSetup(scenarioInfo);
#line 405
 testRunner.Given("I have a calculate variable \"[[a]]\" equal to \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 406
 testRunner.And("I have a calculate variable \"[[b]]\" equal to \"20\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 407
 testRunner.And("I have the formula \"Sum([[a]],[[b]],[[c]])\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 408
 testRunner.When("the aggregate calculate tool is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 409
 testRunner.Then("the execution has \"AN\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table1724 = new TechTalk.SpecFlow.Table(new string[] {
                        "fx ="});
            table1724.AddRow(new string[] {
                        "SUM([[var().int]]) = SUM(3)"});
#line 410
 testRunner.And("the debug inputs as", ((string)(null)), table1724, "And ");
#line hidden
            TechTalk.SpecFlow.Table table1725 = new TechTalk.SpecFlow.Table(new string[] {
                        ""});
            table1725.AddRow(new string[] {
                        "[[rs().a]] = 3"});
#line 413
  testRunner.And("the debug output as", ((string)(null)), table1725, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Aggregated Calculation using variables with a no existent value")]
        public virtual void AggregatedCalculationUsingVariablesWithANoExistentValue()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Aggregated Calculation using variables with a no existent value", ((string[])(null)));
#line 417
this.ScenarioSetup(scenarioInfo);
#line 418
 testRunner.Given("I have the formula \"SUM([[a]],[[b]])\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 419
 testRunner.When("the aggregate calculate tool is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 420
 testRunner.Then("the execution has \"An\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table1726 = new TechTalk.SpecFlow.Table(new string[] {
                        "fx ="});
            table1726.AddRow(new string[] {
                        "SUM([[a]],[[b]]) ="});
#line 421
 testRunner.And("the debug inputs as", ((string)(null)), table1726, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Aggregate all recordset values to all recordset complex with calculation multiple" +
            " recordset star")]
        public virtual void AggregateAllRecordsetValuesToAllRecordsetComplexWithCalculationMultipleRecordsetStar()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Aggregate all recordset values to all recordset complex with calculation multiple" +
                    " recordset star", ((string[])(null)));
#line 426
this.ScenarioSetup(scenarioInfo);
#line 427
 testRunner.Given("I have a calculate variable \"[[rec(1).set]]\" equal to \"10\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 428
 testRunner.And("I have a calculate variable \"[[rec(2).set]]\" equal to \"20\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 429
 testRunner.And("I have a calculate variable \"[[rec(3).set]]\" equal to \"30\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 430
 testRunner.And("I have a calculate variable \"[[rec(1).val]]\" equal to \"10\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 431
 testRunner.And("I have a calculate variable \"[[rec(2).val]]\" equal to \"20\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 432
 testRunner.And("I have a calculate variable \"[[rec(3).val]]\" equal to \"30\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 433
 testRunner.And("I have the formula \"[[rec(*).set]]*[[rec(*).val]]\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 434
 testRunner.And("calculate result as \"[[rec(*).total]]\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 435
 testRunner.When("the aggregate calculate tool is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 436
 testRunner.Then("the execution has \"AN\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table1727 = new TechTalk.SpecFlow.Table(new string[] {
                        "fx ="});
            table1727.AddRow(new string[] {
                        "[[rec(*).set]]*[[rec(*).val]] = 10,20,30*10,20,30"});
#line 437
 testRunner.And("the debug inputs as", ((string)(null)), table1727, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Aggregate all recordset values to all recordset complex with calculation multiple" +
            " recordset star addition")]
        public virtual void AggregateAllRecordsetValuesToAllRecordsetComplexWithCalculationMultipleRecordsetStarAddition()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Aggregate all recordset values to all recordset complex with calculation multiple" +
                    " recordset star addition", ((string[])(null)));
#line 441
this.ScenarioSetup(scenarioInfo);
#line 442
 testRunner.Given("I have a calculate variable \"[[rec(1).set]]\" equal to \"10\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 443
 testRunner.And("I have a calculate variable \"[[rec(2).set]]\" equal to \"20\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 444
 testRunner.And("I have a calculate variable \"[[rec(3).set]]\" equal to \"30\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 445
 testRunner.And("I have a calculate variable \"[[rec(1).val]]\" equal to \"10\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 446
 testRunner.And("I have a calculate variable \"[[rec(2).val]]\" equal to \"20\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 447
 testRunner.And("I have a calculate variable \"[[rec(3).val]]\" equal to \"30\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 448
 testRunner.And("I have the formula \"[[rec(*).set]]+[[rec(*).val]]\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 449
 testRunner.And("calculate result as \"[[rec(*).total]]\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 450
 testRunner.When("the aggregate calculate tool is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 451
 testRunner.Then("the execution has \"AN\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table1728 = new TechTalk.SpecFlow.Table(new string[] {
                        "fx ="});
            table1728.AddRow(new string[] {
                        "[[rec(*).set]]*[[rec(*).val]] = 10,20,30+10,20,30"});
#line 452
 testRunner.And("the debug inputs as", ((string)(null)), table1728, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Aggregate all recordset values to all recordset complex with calculation multiple" +
            " recordset star addition to scalar")]
        public virtual void AggregateAllRecordsetValuesToAllRecordsetComplexWithCalculationMultipleRecordsetStarAdditionToScalar()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Aggregate all recordset values to all recordset complex with calculation multiple" +
                    " recordset star addition to scalar", ((string[])(null)));
#line 457
this.ScenarioSetup(scenarioInfo);
#line 458
 testRunner.Given("I have a calculate variable \"[[rec(1).set]]\" equal to \"10\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 459
 testRunner.And("I have a calculate variable \"[[rec(2).set]]\" equal to \"20\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 460
 testRunner.And("I have a calculate variable \"[[rec(3).set]]\" equal to \"30\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 461
 testRunner.And("I have a calculate variable \"[[rec(1).val]]\" equal to \"10\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 462
 testRunner.And("I have a calculate variable \"[[rec(2).val]]\" equal to \"20\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 463
 testRunner.And("I have a calculate variable \"[[rec(3).val]]\" equal to \"30\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 464
 testRunner.And("I have the formula \"[[rec(*).set]]+[[rec(*).val]]\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 465
 testRunner.And("calculate result as \"[[total]]\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 466
 testRunner.When("the aggregate calculate tool is executed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 467
 testRunner.Then("the execution has \"AN\" error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table1729 = new TechTalk.SpecFlow.Table(new string[] {
                        "fx ="});
            table1729.AddRow(new string[] {
                        "[[rec(*).set]]*[[rec(*).val]] = 10,20,30+10,20,30"});
#line 468
 testRunner.And("the debug inputs as", ((string)(null)), table1729, "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
